### ISSUE TITLE
Forms not showing

### ISSUE THREAD

**Issue by mousasya3** [matthiask/django-newsletter-subscription#5]
I have created a table as you said in the models with two more fields : country and city
and registered it in admin but not showing in the newsletter subscription form it shows just the email and the action
can you show how to do to a custom form for my additional feilds and thanks

**Comment by matthiask** [comment]
https://github.com/matthiask/django-newsletter-subscription/blob/master/newsletter_subscription/templates/newsletter_subscription/form.html

You have to add your own copy of `newsletter_subscription/form.html` to your project containing those fields. The default template only shows `email` and `action.`.

**Comment by mousasya3** [comment]
I did, I tried to add a `{% form_item form.country %}` and it gives me a 404 error
Can you tell me how to put an additional field?

**Comment by matthiask** [comment]
The 404 cannot have anything to do with the new form item. There's something else amiss, and it's really hard to debug this from a distance.

**Comment by mousasya3** [comment]
OK thanks I will try my best to fix it

**Comment by mousasya3** [comment]
I have enabled the debug and I have end up with this error 
`'str' object has no attribute 'field'`

**Comment by matthiask** [comment]
This happens when you use towel's `{% form_item %}` template tag with a form field which does not exist on the form itself. (i.e. `{% form_item form.field_which_does_not_exist_on_the_form %}`)
